# Generated by Django 4.1.3 on 2022-11-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='is_completed',
            new_name='successful',
        ),
    ]
